config/routes.rb
Rails.application.routes.draw do

  root 'lamma#welcome'

  get '/welcome' => 'lamma#welcome'
  get '/thecouple' => 'lamma#thecouple'
  get '/theproposal' => 'lamma#theproposal'
  get '/weddinginformation' => 'lamma#weddinginformation'
  get '/weddingparty' => 'lamma#weddingparty'
  get '/accomodations' => 'lamma#accomodations'
  get '/messagewall' => 'lamma#messagewall'
  get '/registry' => 'lamma#registry'
  get '/rsvp' => 'lamma#rsvp'

  resources :message, :except => [:create]
  post '/message' => 'message#create', as: 'messages'

end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lamma_controller.rb
class LammaController < ApplicationController

  def welcome
  end

  def thecouple
  end

  def theproposal
  end

  def helen
  end

  def lawrence
  end

  def weddinginformation
  end

  def weddingparty
  end

  def accomodations
  end

  def messagewall
    @message = Message.new
    list = Message.all
    @messages = list.reverse
  end

  def contact
  end

  def registry
  end

  def rsvp
  end

  def email
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController

  def new
    @message = Message.new
    @messages = Message.all
  end

  def create
    message = Message.create(messages_params)
    redirect_to messagewall_path
  end

  private

  def messages_params
    params.require(:message).permit(:from, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/lamma/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "night-forest-wallpaper-14-hd-background.jpg", {alt: "..."} %>
      <div class="carousel-caption">

      </div>
    </div>
    <div class="item">
      <%= image_tag "spectacular-sunrise-hd-wallpaper-334329.jpg", {alt: "..."} %>
      <div class="carousel-caption">

      </div>
    </div>
    <div class="item">
      <%= image_tag "golden-gate-from-san-francisco-1440x900.jpg", {alt: "..."} %>
      <div class="carousel-caption">

      </div>
    </div>
  </div>

app/views/lamma/_navbar.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/welcome" class="navbar-brand navbar-left logo">H&L</a>
    </div>
    <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
      <ul class="nav navbar-nav nav">
        <li>
          <%= link_to "The Couple", thecouple_path %>
        </li>
        <li>
          <%= link_to "The Proposal", theproposal_path %>
        </li>
        <li>
          <%= link_to "Wedding Party", weddingparty_path %>
        </li>
        <li>
          <%= link_to "Ceremony and Reception", weddinginformation_path %>
        </li>
        <li>
          <%= link_to "Accomodations", accomodations_path %>
        </li>
        <li>
          <%= link_to "Leave a Message", messagewall_path %>
        </li>
        <li>
          <%= link_to "RSVP", rsvp_path %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/lamma/_new_message.html.erb
<div class="modal fade" id="new_message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for :message, url: messages_path do |f| %>
      <div class="modal-body">
        <h1 class="cursive">Leave us a Message!</h1>
            <%= f.label :text %>:<br />
            <%= f.text_area :text, {size: "25x5"} %><br />
            <%= f.label :from %>:<br />
            <%= f.text_field :from %><br /><br />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Send", class:"btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lamma/accomodations.html.erb
<section class="regular medium">
  <h1 class="cursive">Accomodations</h1>
  <p>
    We will NOT be reserving a block of hotel rooms, but if you will be joining us from out of town, here are a few accomodations that we recommend for you to book in advance.
  </p>
  <ul>
    <li><a href="http://www.marriott.com/hotels/travel/oakdt-oakland-marriott-city-center/"><h3>Oakland Marriott City Center</h3></a>
      <p class="medium">
        <a href="https://maps.google.com?q=1001+Broadway+Oakland+California+94607" target="_blank">1001 Broadway Oakland, California 94607</a>
      </p>
      <img src="http://cdn3.agoda.net/hotelimages/947/94718/94718_1208210842007279964_STD.jpg" class="hotelpics"/><br><br>
      <p class="party-text">
        This is the closest hotel to the venue at only a 5 minute drive and is located in downtown Oakland near Chinatown.  The hotel is about 25 minutes drive from San Francisco.  It is also located close to the 12st Street Oakland City Center BART station with a 32 minute BART ride to downtown San Francisco.
      </p>
    </li>
    <li><a href="http://www.jdvhotels.com/hotels/california/san-francisco-hotels/waterfront-hotel/"><h3>Waterfront Hotel</h3></a>
      <p class="medium">
        <a href="https://maps.google.com?q=10+Washington+Street+Oakland+CA+94607" target="_blank">10 Washington Street, Oakland, California 94607</a>
      </p>
      <img src="http://www.jdvhotels.com/content/uploads/2014/06/Exterior3-600x600.jpg" height="300" class="hotelpics"/><br><br>
      <p class="party-text">
        The Waterfront Hotel is located near Oakland's beautiful Jack London Square and overlooks the San Francisco Bay.  You can take a ferry from Jack London Square to San Francisco from here.  It is also only an 8 minute drive from the wedding venue.
      </p>
    </li>
  </ul>
</section>

app/views/lamma/adminrsvp.html.erb
<section class="regular medium">
  <h1 class="cursive">Responses</h1>
  <div class="list-group">
    <% if @responses %>
      <% @responses.each do |response| %>
        <div class="messages list-group-item">
          <p>
            <%= response.first %> <%= response.last %>
          </p>
          <p>
            <%= response.meal %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/lamma/messagewall.html.erb
<%= render partial: "new_message" %>
<section class="regular overflow-hidden medium">
  <h1 class="cursive">Messages for Helen & Lawrence</h1>

  &nbsp;&nbsp;&nbsp;&nbsp;<a href="#" data-toggle="modal" data-target="#new_message">Leave us a Message!</a>
  <div class="list-group">
    <% if @messages %>
      <% @messages.each do |message| %>
        <div class="messages list-group-item">
          <p>
            <%= message.text %>
          </p>
          <p>
            - <%= message.from %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/lamma/rsvp.html.erb
<script>
 new WOW().init();
</script>

<section class="regular medium">

  <div class="party-sections">
    <h1 class="cursive">R.S.V.P.</h1>
    <p>
      Please Visit our RSVP page to respond to our event.  We really hope you can make it!
    </p>
    <p>
      <a href="http://teamlamma.rsvpify.com/" target="_blank">RSVP Here!</a>
    </p>
    <h3>About the Kids:</h3>
    <p>
      We love kids!  But... we'd prefer that you leave them at home for our wedding as space is limited.  If you have a little one or one you can't find a sitter for please let us know and we'll do our best to make accomodations as space becomes available.
    </p>
    <br>
    <div class="flip-container wow fadeInDown">
      <div class="polaroids rotate-right">
        <%= image_tag "helenlawrenceframe.png", {class: "polaroid-picture"} %>
        R • S • V • P
      </div>
    </div>

  </div>
</section>

app/views/lamma/thecouple.html.erb
<script>
 new WOW().init();
</script>

<section class="regular medium">
  <h1 class="cursive">The Bride</h1>
  <div class="party-sections">
    <div class="flip-container wow fadeInLeft">
      <div class="polaroids rotate-right fl-lf">
        <%= image_tag "helen.jpg", {class: "polaroid-picture"} %>
        The Bride
      </div>
    </div>
    <div class="party-text fl-lf">
      <p>
        I was born and raised in Southern California in a city called Alhambra, otherwise known as the 626.  I went to the Univeristy of California, Irvine for my undergraduate degree in Chemistry while pursuing a career in veterinary medicine.  After college, I moved to the bay area for a change of scene and shortly after I decided to make a career change to the pharmaceuticals industry.  I had been working at a pharmaceuticals company in South San Francisco when I met Lawrence....

      </p>
    </div>
  </div>
  <h1 class="cursive">The Groom</h1>
  <div class="party-sections">
    <div class="party-text fl-lf">
      <p>
        I was a budding young attorney who had been working for only a year when I met Helen.&nbsp;&nbsp;Since then my life has changed so much and thankfully for the better.
      </p>
      <p>
        Before meeting Helen I grew up in Millbrae, CA where I met some of my best friends, most of whom will be standing next to me at the wedding as my groomsmen.  I went to University of Arizona for college and to Sacramento for law school at the University of the Pacific.
      </p>
      <p>
        I'm so thankful to be making this journey with Helen and can't wait for more exciting adventures to come.
      </p>
    </div>
    <div class="flip-container wow fadeInRight">
      <div class="polaroids rotate-left fl-lf">
        <%= image_tag "lawrence.jpg", {class: "polaroid-picture"} %>
        The Groom
      </div>
    </div>
  </div>
  <h1 class="cursive">Together</h1>
  <div>
    <p>
      Helen and Lawrence met in June 2010 as each other's first eHarmony dates.  Lawrence assured Helen that they could just go out for coffee, but left it open for more.  That first date consisted of coffee, burritos, Toy Story 3, boba and eggettes.  Possibly a precursor to what they like to do most often? (Watch Movies and Eat!)
    </p>
    <p>
      Since that date they have traveled all around the country to cities like Honolulu, New York, Orlando, Chicago, Philadelphia and San Diego.
    </p>
    <p>
      Along for the ride of their adventures has been their adorable little dog Penny whom they rescued in 2011.  Penny has been a wonderful dog and a perfect addition to their little family.
    </p>
    <p>
      They've gone through their share of ups and downs, saying goodbye to loved ones who have passed on and going through the stresses of career changes.  But they've come out the other side better than ever.  What's most important is that they realized that through all those trials they are made stronger when they're together.
    </p>
    <p>
      Lawrence proposed to Helen on November 23, 2013 and as you might've guessed she said yes!
    </p>
  </div><br>
  <div class="ft-none">
    <div class="flip-container ft-none wow fadeInDown" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids rotate-right">
            <%= image_tag "us.jpg", {class: "polaroid-picture"} %>
            Lawrence & Helen
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids rotate-left">
            <%= image_tag "back.jpg", {class: "polaroid-picture"} %>
            10 • 10 • 15
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/lamma/theproposal.html.erb
<section class="regular medium">
  <h1 class="cursive">The Proposal</h1>
  <p>

  </p>
  <iframe src="https://www.youtube.com/embed/Wzd33Hcsme0" frameborder="0" allowfullscreen></iframe>
  <br><br>
  <h2 class="cursive">The Story</h2>
  <p>
    I originally wanted to have the proposal on a beach but at the last minute we had to change plans because Helen's mom didn't want us take all our dogs into her SUV! Haha.  Helen's sister Janet helped me plan it out and I had made a small frame to attach to Penny's harness and I kept it in my huge jacket on a warm Los Angeles day.
  </p>
  <p>
    The plan was to tell Helen to run off so I could attach the harness and Penny would run after her.  Problem was, Helen wanted me to run off instead!  Good thing Janet was thinking on her feet and she had Helen walk over to the side so while they were walking I nervously attached the harness and watched Penny run as fast as she could to Helen.
  </p>
  <p>
    Thankfully, she said yes!
  </p>
  <div class="ft-none">
    <div class="flip-container ft-none" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids rotate-left">
            <%= image_tag "proposalframe.jpg", {class: "polaroid-picture"} %>
            Will You Marry Me?
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids rotate-right">
            <%= image_tag "helen_ring.png", {class: "polaroid-picture"} %>
            Yes!
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/lamma/weddinginformation.html.erb
<script>
 new WOW().init();
</script>

<section class="regular">

  <h1 class="cursive">Ceremony and Reception</h1><br>
  <div class="party-sections">
    <div class="party-text fl-lf">
      <h3>The Venue</h3>
      <p>
        The wedding will be held at The Terrace Room in Oakland, California overlooking Lake Merritt.
      </p>
      <p class="medium">
        <b>The Terrace Room Restaurant</b><br>
        <a href="https://maps.google.com?q=Terrace+Room+Restaurant+1800+Madison+Street+Oakland+CA" target="_blank">1800 Madison Street<br>
        Oakland, CA 94612</a>
      </p>
      <h3>Ceremony and Reception</h3>
      <p>
        The ceremony will begin promptly at <u>5:00 PM</u>. Cocktail hour and Reception immediately follows the ceremony at the same location.
      </p>
      <h3>Parking</h3>
      <p>
        There is plenty of street parking and most of the open spots will be surrounding Lake Merritt.
      </p>
      <p>
        The nearest parking garage is about a 10 minute walk at the Kaiser Center Parking Garage. located under the
      </p>
      <p class="medium">
        <b>Kaiser Center Parking Garage</b><br/>
        <a href="https://maps.google.com?q=Kaiser+Center+Parking+Garage+300+Lakeside+Drive+Oakland+CA+94666" target="_blank">300 Lakeside Drive<br/>
        Oakland, CA 94666</a>
      </p>
    </div>
    <div class="flip-container wow fadeInDown" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids fl-lf rotate-right">
            <%= image_tag "terrace_room.jpg", {class: "polaroid-picture"} %>
            The Terrace Room Restaurant
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids fl-lf rotate-left">
            <%= image_tag "night_terrace_room.jpg", {class: "polaroid-picture"} %>
            Lake Merritt at night
          </div>
        </div>
      </div>
    </div>
  </div>
  <p>
    <h3>Getting There</h3>
  </p>
  <h4>Coming from San Francisco or North Peninsula</h4>
  <p>
    - Head East on the I-80, Bay Bridge towards Oakland.<br>
    - Take 580 East towards Hayward.<br>
    - Take the Harrison Street Exit.<br>
    - Turn Right on Harrison Street.<br>
    - Harrison will turn into Madison Street after the 19th Street intersection.<br>
    - The Terrace Room will be directly to your left after you cross 19th Street.
  </p>
  <h4>Coming from the South Peninsula</h4>
  <p>
    - From 101 take 92 East, San Mateo Bridge towards Hayward.<br>
    - Take the Exit to 880 North towards Oakland.<br>
    - Take the Oak Street Exit towards Lakeside Drive.<br>
    - Turn Right on Oak Street.<br>
    - Continue onto Lakeside Drive.<br>
    - Turn left on Madison Street.<br>
    - Terrace Room should be to your left after you turn on Madison.
  </p>
  <h4>Coming from San Jose or East Bay</h4>
  <p>
    - Take 880 North towards Oakland.<br>
    - Take the Oak Street Exit towards Lakeside Drive.<br>
    - Turn Right on Oak Street.<br>
    - Continue onto Lakeside Drive.<br>
    - Turn left on Madison Street.<br>
    - Terrace Room should be to your left after you turn on Madison.
  </p>



</section>

app/views/lamma/welcome.html.erb
<script>
 new WOW().init();
</script>

<div class="ground">
  <div class="mobile-background">
  <a href="#welcome"><div class="intro-section cursive intro" id="text">
  </div></a>

  <div class="welcome-bottom regular" id="front">
    <div class="flip-container wow fadeInLeft" id="welcome" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids fl-lf rotate-right">
            <%= image_tag "disneyland.jpg", {class: "polaroid-picture"} %>
            Happiest Place on Earth...
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids fl-lf rotate-left">
            <%= image_tag "chicago.jpg", {class: "polaroid-picture"} %>
            Rawr!
          </div>
        </div>
      </div>
    </div>
    <div class="flip-container wow fadeInLeftBig" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids fl-lf rotate-left">
            <%= image_tag "bubbles.jpg", {class: "polaroid-picture"} %>
            Bubbles!
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids fl-lf rotate-right">
            <%= image_tag "LH.jpg", {class: "polaroid-picture"} %>
            Lawrence + Helen
          </div>
        </div>
      </div>
    </div>
    <div class="flip-container wow fadeInRightBig" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids fl-lf rotate-right">
            <%= image_tag "christmas.jpg", {class: "polaroid-picture"} %>
            Christmas with Penny
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids fl-lf rotate-left">
            <%= image_tag "giants_game.jpg", {class: "polaroid-picture"} %>
            Go Giants!
          </div>
        </div>
      </div>
    </div>
    <div class="flip-container wow fadeInRight" ontouchstart="this.classList.toggle('hover');">
      <div class="flipper">
        <div class="front">
          <!-- front content -->
          <div class="polaroids fl-lf rotate-left">
            <%= image_tag "engaged.jpg", {class: "polaroid-picture"} %>
            Penny and the Ring!
          </div>
        </div>
        <div class="back">
          <!-- back content -->
          <div class="polaroids fl-lf rotate-right">
            <%= image_tag "SFHeart.jpg", {class: "polaroid-picture"} %>
            Welcome to San Francisco!
          </div>
        </div>
      </div>
    </div>
    <div class="welcome-message">
      <h1 class="cursive">Welcome!</h1>
      <p class="medium-large">
        Whether we see you on our special day or not, we want to extend a heartfelt thank you to all of you, our friends and family, for supporting us and loving us unconditionally.  We know that none of this is possible without you and we hope to see you all soon!
      </p><br>
      <div class="cursive signature">
        Lawrence & Helen
      </div>
      <br><br><br>
      <p id="footer">website design by lawrence ma</p>
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamLamma</title>
  <link rel="icon" type="image/ico" href="assets/favicon.ico" />
  <link href='https://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Codystar' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
  <!-- Optional theme -->
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "navbar" %>
  <%= yield %>

</body>
</html>